# Generated by Django 5.0.6 on 2025-05-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gen_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaeq', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marcaeq'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixeq', models.CharField(max_length=2, unique=True)),
                ('tipoeq', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo equipo',
                'verbose_name_plural': 'Tipo equipos',
                'ordering': ['tipoeq'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloeq', models.CharField(max_length=150)),
                ('marcaeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.marcaequipo')),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.tipoequipo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['modeloeq'],
            },
        ),
        migrations.AddField(
            model_name='marcaequipo',
            name='tipoeq',
            field=models.ManyToManyField(to='maq_equipo.tipoequipo'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinterno', models.CharField(max_length=4)),
                ('nombreeq', models.CharField(max_length=100)),
                ('patente', models.CharField(blank=True, max_length=10)),
                ('anioeq', models.CharField(max_length=4)),
                ('fechacompra', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.empresa')),
                ('marcaeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.marcaequipo')),
                ('modeloeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.modeloequipo')),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.tipoequipo')),
            ],
        ),
    ]
