# Generated by Django 5.0.6 on 2025-05-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gen_settings', '0001_initial'),
        ('maq_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_equipo.tipoequipo')),
            ],
            options={
                'verbose_name': 'Plantilla de Ficha Técnica',
                'verbose_name_plural': 'Plantillas de Fichas Técnicas',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='SeccionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=150)),
                ('tipoeq', models.ManyToManyField(to='maq_equipo.tipoequipo')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('especificacion', models.CharField(max_length=150)),
                ('tipodato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.tipodato')),
                ('unidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.unidadmedida')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.seccionficha')),
            ],
            options={
                'verbose_name': 'Especificación',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['especificacion'],
            },
        ),
        migrations.CreateModel(
            name='SeccionPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='maq_fichatecnica.plantillafichatecnica')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.seccionficha')),
            ],
            options={
                'verbose_name': 'Sección de Plantilla',
                'verbose_name_plural': 'Secciones de Plantilla',
                'ordering': ['orden'],
                'unique_together': {('plantilla', 'seccion')},
            },
        ),
    ]
