# Generated by Django 5.2 on 2025-05-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaeq', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marcaeq'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixeq', models.CharField(max_length=2, unique=True)),
                ('tipoeq', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo equipo',
                'verbose_name_plural': 'Tipo equipos',
                'ordering': ['tipoeq'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloeq', models.CharField(max_length=150)),
                ('marcaeq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_fichatecnica.marcaequipo')),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_fichatecnica.tipoequipo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['modeloeq'],
            },
        ),
        migrations.AddField(
            model_name='marcaequipo',
            name='tipoeq',
            field=models.ManyToManyField(to='maq_fichatecnica.tipoequipo'),
        ),
    ]
