# Generated by Django 5.2 on 2025-05-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_fichatecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('seccioneq', models.CharField(max_length=150)),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_fichatecnica.tipoequipo')),
            ],
        ),
    ]
