# Generated by Django 5.2 on 2025-05-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0006_tipodato'),
        ('maq_fichatecnica', '0002_seccionficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.tipoequipo')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fichaTecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.fichatecnica')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField()),
                ('valorPredet', models.CharField(blank=True, max_length=255, null=True)),
                ('esRequerido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('tipoDato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.tipodato')),
                ('unidadMedida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gen_settings.unidadmedida')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.seccion')),
            ],
            options={
                'verbose_name': 'Especificación',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['seccion__orden', 'orden'],
            },
        ),
        migrations.DeleteModel(
            name='SeccionFicha',
        ),
    ]
