# Generated by Django 5.2 on 2025-05-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maq_fichatecnica', '0003_fichatecnica_seccion_especificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacion',
            name='esRequerido',
        ),
        migrations.RemoveField(
            model_name='especificacion',
            name='valorPredet',
        ),
    ]
