# Generated by Django 5.2.1 on 2025-05-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maq_fichatecnica', '0004_remove_especificacion_esrequerido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='tipoeq',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='fichaTecnica',
        ),
        migrations.DeleteModel(
            name='Especificacion',
        ),
        migrations.DeleteModel(
            name='FichaTecnica',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
