# Generated by Django 5.2.1 on 2025-05-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0007_alter_unidadmedida_options'),
        ('maq_fichatecnica', '0005_remove_fichatecnica_tipoeq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=150)),
                ('tipoeq', models.ManyToManyField(to='maq_fichatecnica.tipoequipo')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=150)),
                ('tipodato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.tipodato')),
                ('unidadmedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_settings.unidadmedida')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maq_fichatecnica.seccionficha')),
            ],
            options={
                'verbose_name': 'Especificación',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['especificacion'],
            },
        ),
    ]
