# Generated by Django 5.2.1 on 2025-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_fichatecnica', '0006_seccionficha_especificacionficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionficha',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
