# Generated by Django 5.0.6 on 2025-05-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
