# Generated by Django 5.2 on 2025-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0005_alter_empresa_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Dato',
                'verbose_name_plural': 'Tipos de Dato',
            },
        ),
    ]
