# Generated by Django 5.2.1 on 2025-05-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0006_tipodato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
