# Generated by Django 5.1.5 on 2025-01-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaeq', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixeq', models.CharField(max_length=2)),
                ('tipoeq', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloeq', models.CharField(max_length=100)),
                ('marcaeq_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.marcaequipo')),
                ('tipoeq_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.tipoequipo')),
            ],
        ),
    ]
