# Generated by Django 5.1.5 on 2025-02-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoequipo',
            name='prefixeq',
            field=models.CharField(max_length=2, unique=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='tipoeq',
            field=models.CharField(max_length=100, verbose_name='Tipo equipo'),
        ),
    ]
